### ISSUE TITLE
TypeError: Cannot read property 'project' of undefined

### ISSUE THREAD

**Issue by artemgurzhii** [truecoach/ember-cli-memory-leak-detector#8]
```
**Versions:**
Ember | 3.16.10
Ember Data | 3.16.9
Ember Simple Auth | 3.0.1
Testem | 3.2.0
```

```
**Stack trace:**
 stack: TypeError: Cannot read property 'project' of undefined
    at readConfig (/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector/lib/attach-middleware.js:129:20)
    at attachMiddleware (/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector/lib/attach-middleware.js:7:18)
    at Class.testemMiddleware (/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector/index.js:43:5)
    at /builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:187:9
    at Array.forEach (<anonymous>)
    at Server.injectMiddleware (/builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:186:19)
    at Server.createExpress (/builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:137:10)
    at Server.start (/builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:41:10)
    at App.startServer (/builds/chattermill/frontend/frontend/node_modules/testem/lib/app.js:232:24)
    at App.getServer (/builds/chattermill/frontend/frontend/node_modules/testem/lib/app.js:236:17)
    at /builds/chattermill/frontend/frontend/node_modules/testem/lib/app.js:74:38
    at tryCatcher (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/util.js:16:23)
    at /builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/promise.js:604:18)
```

Error is being rased [here](https://github.com/truecoach/ember-cli-memory-leak-detector/blob/main/lib/attach-middleware.js#L129) and is being called from [here](https://github.com/truecoach/ember-cli-memory-leak-detector/blob/main/index.js#L43).

I was trying to debug and added `console.log({ lorem: this });` [here](https://github.com/truecoach/ember-cli-memory-leak-detector/blob/main/index.js#L43).

Here are my results
```
  lorem: Class {
    _super: undefined,
    parent: Project {
      root: '/builds/chattermill/frontend/frontend',
      pkg: [Object],
      ui: [UI],
      cli: [CLI],
      addonPackages: [Object: null prototype],
      addons: [Array],
      liveReloadFilterPatterns: [],
      bowerDirectory: 'bower_components',
      configCache: [Map],
      _watchmanInfo: [Object],
      _instrumentation: [Instrumentation],
      emberCLIVersion: [Function: emberCLIVersion],
      _nodeModulesPath: null,
      packageInfoCache: [PackageInfoCache],
      _packageInfo: [PackageInfo],
      _addonsInitialized: true,
      generateTestFile: [Function]
    },
    project: Project {
      root: '/builds/chattermill/frontend/frontend',
      pkg: [Object],
      ui: [UI],
      cli: [CLI],
      addonPackages: [Object: null prototype],
      addons: [Array],
      liveReloadFilterPatterns: [],
      bowerDirectory: 'bower_components',
      configCache: [Map],
      _watchmanInfo: [Object],
      _instrumentation: [Instrumentation],
      emberCLIVersion: [Function: emberCLIVersion],
      _nodeModulesPath: null,
      packageInfoCache: [PackageInfoCache],
      _packageInfo: [PackageInfo],
      _addonsInitialized: true,
      generateTestFile: [Function]
    },
    ui: UI {
      spinner: [Ora],
      progress: false,
      actualOutputStream: [WriteStream],
      outputStream: [DestroyableTransform],
      inputStream: [ReadStream],
      errorStream: [WriteStream],
      errorLog: [],
      writeLevel: 'INFO',
      errorReport: null,
      ci: false
    },
    addonPackages: [Object: null prototype] {
      'ember-cli-babel': [AddonInfo],
      'ember-cli-htmlbars': [AddonInfo]
    },
    addons: [ [Class], [Class] ],
    registry: Registry {
      registry: [Object],
      instantiatedPlugins: [Array],
      availablePlugins: [Object],
      app: [Circular],
      pluginTypes: [Object]
    },
    _nodeModulesPath: null,
    treePaths: {
      app: 'app',
      src: 'src',
      styles: 'app/styles',
      templates: 'app/templates',
      addon: 'addon',
      'addon-styles': 'addon/styles',
      'addon-templates': 'addon/templates',
      vendor: 'vendor',
      'test-support': 'test-support',
      'addon-test-support': 'addon-test-support',
      public: 'public'
    },
    treeForMethods: {
      app: 'treeForApp',
      src: 'treeForSrc',
      addon: 'treeForAddon',
      'addon-styles': 'treeForAddonStyles',
      'addon-templates': 'treeForAddonTemplates',
      'addon-test-support': 'treeForAddonTestSupport',
      public: 'treeForPublic',
      styles: 'treeForStyles',
      templates: 'treeForTemplates',
      'test-support': 'treeForTestSupport',
      vendor: 'treeForVendor'
    },
    packageInfoCache: PackageInfoCache {
      ui: [UI],
      entries: [Object: null prototype],
      projects: [Array],
      valid: false
    },
    _packageInfo: PackageInfo {
      pkg: [Object],
      realPath: '/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector',
      cache: [PackageInfoCache],
      errors: [ErrorList],
      addonMainPath: '/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector/index.js',
      inRepoAddons: undefined,
      internalAddons: undefined,
      cliInfo: undefined,
      dependencyPackages: [Object: null prototype],
      devDependencyPackages: undefined,
      nodeModules: [NodeModulesList],
      valid: true,
      mayHaveAddons: true,
      _hasDumpedInvalidAddonPackages: true,
      processed: true,
      addonConstructor: [Function]
    },
    root: '/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector',
    _addonsInitialized: true,
    options: { babel: {}, 'ember-cli-babel': [Object] },
    __originalOptions: { babel: {}, 'ember-cli-babel': [Object] },
    constructor: [Function: Class] { _meta_: [Object] }
  }
}
not ok 1 [undefined ms] - TypeError
    ---
        message: >
            Cannot read property 'project' of undefined
    ...

1..1
# tests 1
# pass  0
# skip  0
# todo  0
# fail  1
```

Is that something I doing wrong or something wrong on the addon side?

**Comment by steveszc** [comment]
@artemgurzhii 
Can you try again with `ember-cli-memory-leak-detector@0.1.2`?

**Comment by artemgurzhii** [comment]
@steveszc other issue is happening

```
 - stack: TypeError: Cannot read property 'trees' of undefined
    at getAppClasses (/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector/lib/attach-middleware.js:19:42)
    at attachMiddleware (/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector/lib/attach-middleware.js:8:19)
    at Class.testemMiddleware (/builds/chattermill/frontend/frontend/node_modules/ember-cli-memory-leak-detector/index.js:43:5)
    at /builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:187:9
    at Array.forEach (<anonymous>)
    at Server.injectMiddleware (/builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:186:19)
    at Server.createExpress (/builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:137:10)
    at Server.start (/builds/chattermill/frontend/frontend/node_modules/testem/lib/server/index.js:41:10)
    at App.startServer (/builds/chattermill/frontend/frontend/node_modules/testem/lib/app.js:232:24)
    at App.getServer (/builds/chattermill/frontend/frontend/node_modules/testem/lib/app.js:236:17)
    at /builds/chattermill/frontend/frontend/node_modules/testem/lib/app.js:74:38
    at tryCatcher (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/util.js:16:23)
    at /builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/builds/chattermill/frontend/frontend/node_modules/bluebird/js/release/promise.js:604:18)
```

raised from [that line](https://github.com/truecoach/ember-cli-memory-leak-detector/blob/main/lib/attach-middleware.js#L19)
